### ISSUE TITLE
Drive link for Pretrained models

### ISSUE THREAD

**Issue by mshaheryar91** [Talented-Q/POSTER_V2#2]
Dear authors, please upload the pretrained model on goggle drive, as i am also facing difficulty for downloading it.

**Comment by Talented-Q** [comment]
> Dear authors, please upload the pretrained model on goggle drive, as i am also facing difficulty for downloading it.

Thank you for your interest in our paper and we will upload the pre-training model to Google drive soon.

**Comment by mshaheryar91** [comment]
Thanks for it
