### ISSUE TITLE
Some questions about testing code

### ISSUE THREAD

**Issue by winner-4** [Talented-Q/POSTER_V2#21]
I am writing to express my keen interest in your POSTER++ project proposal. I am currently interested in utilizing this model to generate emoticon labels for my dataset. Could you kindly provide the necessary testing code for this purpose?

**Comment by cbiras** [comment]
@winner-4 did you manage to run an inference using the provided models? I am trying to run an inference on a webcam feed, and the results are kinda poor, the model predicts only 1-2 classes, no matter what expression I have. Is there any pre-processing I am missing?

**Comment by winner-4** [comment]
I did not use webcam inference; I performed inference on facial images, and the results are as expected. I'm not sure what differences might exist in this context. However, I can show you my preprocessing steps. 
![image](https://github.com/Talented-Q/POSTER_V2/assets/77573973/6684c2c8-eba5-416b-81d4-8274ca745954)

**Comment by winner-4** [comment]
![image](https://github.com/Talented-Q/POSTER_V2/assets/77573973/6577bb01-d325-4735-a9ad-08fa88871e17)

**Comment by Yhc-777** [comment]
@winner-4 Could you provide the complete predict.py file you wrote? I got some problems in predicting singe image... Thank you!email: 595390870@qq.com
