### ISSUE TITLE
About the test: where is mobilefacenet_model_best.pth.tar

### ISSUE THREAD

**Issue by cyinen** [Talented-Q/POSTER_V2#5]
Dear authors,
   Thanks for you sharing your excellent work. 
   I can't test the pretrain model without the mobilefacenet_model_best.pth.tar, could you provide it?
Thanks again!

**Comment by winner-4** [comment]
> Found it! https://github.com/cosanlab/feat/releases/download/v0.1/mobilefacenet_model_best.pth.tar

Hello, may I ask if you can provide a download link for "ir50.pth"? Due to specific reasons, I am unable to download it from Baidu Disk or Google Drive.
